language: elixir
elixir:
  - 1.7
otp_release:
  - 21.0
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
script:
  - mix format --check-formatted
  - mix test
